"""empty message

Revision ID: 768e5b21d58b
Revises: 40275026a0c0
Create Date: 2025-04-10 22:18:28.468878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768e5b21d58b'
down_revision = '40275026a0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'VIDEO', name='typeenum'), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=250), nullable=False))
        batch_op.drop_column('text')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=350), nullable=True))
        batch_op.drop_constraint('post_caption_key', type_='unique')
        batch_op.create_unique_constraint(None, ['content'])
        batch_op.drop_column('caption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('post_caption_key', ['caption'])
        batch_op.drop_column('content')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('content')

    op.drop_table('media')
    # ### end Alembic commands ###
